- name: Simple regex replace.
  hosts: localhost
  gather_facts: false
  vars:
    my_conf: '{{ playbook_dir }}/test11.conf'
  tasks:
    - replace:
        path: "{{ my_conf }}"
        regexp: '^(/var/log/apache2/\*\.log)\s+(.*){$'
        replace: '\1 /var/log/apache2/*/*.log {'
      register: results
    - debug:
        var: results

# Replace a line in a file with Ansible, while ensuring that line is present
# https://serverfault.com/questions/985701/replace-a-line-in-a-file-with-ansible-while-ensuring-that-line-is-present/

# -/var/log/apache2/*.log {
# +/var/log/apache2/*.log /var/log/apache2/*/*.log {
