- hosts: localhost
  gather_facts: no
  tasks:
    - blockinfile:
       path: /scratch/tmp/test
       insertafter: EOF
       block: |3
               - "ww4.xx4.yy4.zz4 hostname4"

# How to add spaces at the begining using ansible playbook
# https://stackoverflow.com/questions/56911698/how-to-add-spaces-at-the-begining-using-ansible-playbook/
