---

- hosts: localhost
  gather_facts: true
  tasks:
    - set_fact:
        al_os_vars_path: "{{ playbook_dir }}"
    - include_role:
        name: vbotka.ansible_lib
        tasks_from: al_include_os_vars_path.yml
    - debug:
        var: test_var_1

- hosts: test_01
  gather_facts: true
  tasks:
    - set_fact:
        al_os_vars_path: "{{ playbook_dir }}"
    - include_role:
        name: vbotka.ansible_lib
        tasks_from: al_include_os_vars_path.yml
    - debug:
        var: test_var_1

...
